pipeline:
  name: lambda
  identifier: lambda
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cdk
        identifier: cdk
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - stepGroup:
                  name: cdk
                  identifier: cdk
                  steps:
                    - step:
                        type: GitClone
                        name: GitClone_1
                        identifier: GitClone_1
                        spec:
                          connectorRef: github
                          build:
                            type: branch
                            spec:
                              branch: main
                    - step:
                        type: AwsCdkBootstrap
                        name: AwsCdkBootstrap_1
                        identifier: AwsCdkBootstrap_1
                        spec:
                          connectorRef: account.harnessImage
                          image: sushanteno8/harness:v4
                          resources:
                            limits:
                              memory: 1000Mi
                              cpu: 1000m
                        timeout: 10m
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: cdknew
            rollbackSteps: []
          serviceDependencies: []
        tags: {}
