pipeline:
  name: lambda-deployment
  identifier: lambdadeployment
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        build: <+input>
  stages:
    - stage:
        name: cdk
        identifier: cdk
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - stepGroup:
                  name: cdk
                  identifier: cdk
                  steps:
                    - step:
                        type: GitClone
                        name: Git CLone
                        identifier: Git_CLone
                        spec:
                          connectorRef: github
                          build:
                            type: branch
                            spec:
                              branch: main
                    - step:
                        type: AwsCdkBootstrap
                        name: AwsCdkBootstrap_1
                        identifier: AwsCdkBootstrap_1
                        spec:
                          connectorRef: account.harnessImage
                          image: cribl/harness-cdk-plugin:latest
                          appPath: harness-cicd/cdk
                          delegateSelectors:
                            - docker-delegate
                        timeout: 10m
                    - step:
                        type: AwsCdkDeploy
                        name: AwsCdkDeploy_1
                        identifier: AwsCdkDeploy_1
                        spec:
                          connectorRef: account.harnessImage
                          image: cribl/harness-cdk-plugin:latest
                          appPath: harness-cicd/cdk
                          provisionerIdentifier: cdk
                        timeout: 10m
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: cdk
            rollbackSteps: []
          serviceDependencies: []
        tags: {}
